# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           ':title'
relative_permalinks: true

# Setup
title:               Praveen Puglia
tagline:             'Web Developer'
description:         'All things JavaScript & CSS. Want to travel the World & beyond!'
url:                 http://praveenpuglia.com
baseurl:             ''

# About/contact
author:
  name:              Praveen Puglia
  url:               https://twitter.com/praveenpugli
  email:             praveenpuglia@gmail.com

# Custom vars
version:             1.1.0
