# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: "blog/:title/"

# Setup
title: Praveen Puglia
tagline: "Web Developer"
description: "Learning about the Web for life."
url: http://praveenpuglia.com
baseurl: ""
markdown: kramdown

# About/contact
author:
  name: Praveen Puglia
  url: http://twitter.com/praveenpuglia
  email: praveenpuglia@gmail.com

# Custom vars
version: 1.1.0
